version: "1.0"
info:
  model: int-scaffold
packages:
- name: FlowTestProject
  gitServerName: KritikasGitHubAccount
  gitUrl: https://github.com/KitNabber/FlowTestProject
  gitUsername: KitNabber
  gitBranch: main
